# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_contas', '0002_conta_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='fixa',
            field=models.CharField(default=b'Nao', max_length=200),
        ),
    ]
