# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_contas', '0003_conta_fixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='fixa',
            field=models.CharField(default='Nao', max_length=200),
        ),
    ]
