# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caixa_geral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operacao', models.CharField(choices=[('1', 'Entrada'), ('2', 'Saida')], max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.CharField(max_length=200)),
                ('id_operacao', models.CharField(max_length=200)),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
