# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chica_caixa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa_geral',
            old_name='desc',
            new_name='descricao',
        ),
    ]
