# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conta_empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operacao', models.CharField(choices=[(b'1', b'Entrada'), (b'2', b'Saida')], max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=300)),
                ('id_operacao', models.CharField(max_length=200)),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
