# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_controle', '0002_conta_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='taxa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.CharField(default=1, max_length=2)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
