# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_controle', '0003_taxa'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxa',
            name='tipo',
            field=models.CharField(choices=[(b'1', b'Credito'), (b'2', b'Debito'), (b'3', b'Elo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
