# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_controle', '0005_auto_20190116_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxa',
            name='tipo',
            field=models.CharField(choices=[(b'1', b'Credito a Vista'), (b'2', b'Credito a Prazo'), (b'3', b'Debito'), (b'4', b'Elo'), (b'4', b'Boleto')], max_length=1),
        ),
    ]
