# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_controle', '0007_auto_20190117_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxa',
            name='tipo',
            field=models.CharField(choices=[(b'1', b'Credito a Vista'), (b'2', b'Credito a Prazo'), (b'3', b'Debito'), (b'4', b'Debito Elo'), (b'5', b'Credito Elo'), (b'6', b'Boleto')], max_length=1),
        ),
    ]
