# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('convenio', models.CharField(choices=[(b'1', b'ISS'), (b'2', b'Estado MS'), (b'3', b'SIAPE'), (b'4', b'EXERCITO')], max_length=1)),
                ('operacao', models.CharField(blank=True, max_length=200, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('pai', models.CharField(blank=True, max_length=200, null=True)),
                ('mae', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_cidade', models.CharField(blank=True, max_length=2, null=True)),
                ('data_nasc', models.DateTimeField(blank=True, null=True)),
                ('natural', models.CharField(blank=True, max_length=200, null=True)),
                ('uf_natural', models.CharField(blank=True, max_length=2, null=True)),
                ('rg', models.CharField(blank=True, max_length=40, null=True)),
                ('expedicao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_exp', models.DateTimeField(blank=True, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=200, null=True)),
                ('especie_beneficio', models.CharField(blank=True, max_length=100, null=True)),
                ('renda', models.CharField(blank=True, max_length=100, null=True)),
                ('cad_senha', models.CharField(blank=True, max_length=100, null=True)),
                ('senha_econsig', models.CharField(blank=True, max_length=100, null=True)),
                ('prec', models.CharField(blank=True, max_length=100, null=True)),
                ('id_mg', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_solicitado', models.CharField(blank=True, max_length=100, null=True)),
                ('n_parcela', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_parcela', models.CharField(blank=True, max_length=100, null=True)),
                ('pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('n_conta', models.CharField(blank=True, max_length=100, null=True)),
                ('t_conta', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
