# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_cliente', '0002_auto_20190107_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
