# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_cliente', '0003_cliente_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
