# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_cliente', '0004_cliente_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='celular',
            new_name='cel',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone',
            new_name='tel',
        ),
    ]
