# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_cliente', '0005_auto_20190107_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='pagamento',
            new_name='f_pagamento',
        ),
    ]
