# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_cliente', '0008_cliente_portabilidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente_portabilidade',
            old_name='banco_prtador',
            new_name='banco_portador',
        ),
        migrations.RenameField(
            model_name='cliente_portabilidade',
            old_name='banco_prtador1',
            new_name='banco_portador1',
        ),
        migrations.RenameField(
            model_name='cliente_portabilidade',
            old_name='banco_prtador2',
            new_name='banco_portador2',
        ),
        migrations.RenameField(
            model_name='cliente_portabilidade',
            old_name='banco_prtador3',
            new_name='banco_portador3',
        ),
    ]
