# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_cliente', '0009_auto_20190107_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='ctt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='ctt1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='ctt2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='ctt3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='liquido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='liquido1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='liquido2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='liquido3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='quitacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='quitacao1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='quitacao2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='quitacao3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='valor_parcela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='valor_parcela1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='valor_parcela2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente_portabilidade',
            name='valor_parcela3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
