# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_cliente', '0002_auto_20181220_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='uf_cidade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
