# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_cliente', '0003_cliente_uf_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
