# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_cliente', '0004_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='liberacao',
            field=models.CharField(choices=[(b'1', b'Ok'), (b'2', b'Bloqueado')], default=1, max_length=1),
        ),
    ]
