# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_caixa', '0002_caixa_geral_dinheiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa_geral',
            name='dinheiro',
        ),
    ]
