# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chica_controle', '0001_initial'),
        ('chica_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pagamento', models.CharField(choices=[(b'1', b'Dinheiro'), (b'2', b'Cartao Debito'), (b'3', b'Cartao Credito'), (b'4', b'Aberto')], max_length=1)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chica_cliente.cliente')),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chica_controle.funcionario')),
                ('serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chica_controle.servico')),
            ],
        ),
    ]
