# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chica_controle', '0001_initial'),
        ('chica_agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servico_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chica_controle.funcionario')),
                ('serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chica_controle.servico')),
            ],
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='func',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='serv',
        ),
        migrations.AddField(
            model_name='agenda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='item_servico',
            field=models.ManyToManyField(to='chica_agenda.servico_item'),
        ),
    ]
