# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chica_agenda', '0003_auto_20181213_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico_item',
            name='cancelado',
            field=models.CharField(choices=[(b'1', b'Sim'), (b'2', b'Nao')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
