# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chica_agenda', '0004_servico_item_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico_item',
            name='cancelado',
            field=models.CharField(choices=[(b'1', b'Nao'), (b'2', b'Sim')], max_length=1),
        ),
    ]
