# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-19 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chica_agenda', '0006_auto_20181214_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='pagamento',
            field=models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Cartao Debito'), ('3', 'Cartao Credito'), ('4', 'Aberto'), ('5', 'Desmarcado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='servico_item',
            name='cancelado',
            field=models.CharField(choices=[('1', 'Nao'), ('2', 'Sim')], default='1', max_length=1),
        ),
    ]
