# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chica_controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ponto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[(b'1', b'Aberto'), (b'2', b'Confirmado')], max_length=1)),
                ('funcionario', models.CharField(max_length=200)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
