# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chica_controle', '0002_ponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='operacao',
            field=models.CharField(choices=[(b'1', b'Entrada'), (b'2', b'Saida')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
