# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chica_controle', '0003_ponto_operacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto',
            old_name='estado',
            new_name='modo',
        ),
    ]
