# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chica_controle', '0005_auto_20181212_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='modo',
        ),
        migrations.AddField(
            model_name='ponto',
            name='estado',
            field=models.CharField(choices=[(b'1', b'Aberto'), (b'2', b'Confirmado')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ponto',
            name='operacao',
            field=models.CharField(max_length=15),
        ),
    ]
