from django.db import models
from django.utils import timezone

# Create your models here.
class cliente(models.Model):
    CV = (
        ('1', 'ISS'),
        ('2', 'Estado MS'),
        ('3', 'SIAPE'),
        ('4', 'EXERCITO'),
    )
    id = models.AutoField(primary_key=True)
    convenio = models.CharField(max_length=1, choices=CV)
    banco_cad = models.CharField(max_length=200, null=True, blank=True)
    operacao = models.CharField(max_length=200, null=True, blank=True)
    beneficio = models.CharField(max_length=200, null=True, blank=True)
    uf_beneficio = models.CharField(max_length=2, null=True, blank=True)
    cpf = models.CharField(max_length=14, null=True, blank=True)
    nome = models.CharField(max_length=200)
    pai = models.CharField(max_length=200, null=True, blank=True)
    mae = models.CharField(max_length=200, null=True, blank=True)
    endereco = models.CharField(max_length=200, null=True, blank=True)
    numero = models.CharField(max_length=30, null=True, blank=True)
    complemento = models.CharField(max_length=200, null=True, blank=True)
    bairro = models.CharField(max_length=100, null=True, blank=True)
    cidade = models.CharField(max_length=100, null=True, blank=True)
    uf_cidade = models.CharField(max_length=2, null=True, blank=True)
    cep = models.CharField(max_length=100, null=True, blank=True)
    data_nasc = models.DateTimeField(null=True, blank=True)
    natural = models.CharField(max_length=200, null=True, blank=True)
    uf_natural = models.CharField(max_length=2, null=True, blank=True)
    rg = models.CharField(max_length=40, null=True, blank=True)
    expedicao = models.CharField(max_length=100, null=True, blank=True)
    data_exp = models.DateTimeField(null=True, blank=True)
    escolaridade = models.CharField(max_length=200, null=True, blank=True)
    especie_beneficio = models.CharField(max_length=100, null=True, blank=True)
    renda = models.CharField(max_length=100, null=True, blank=True)
    cad_senha = models.CharField(max_length=100, null=True, blank=True)
    senha_econsig = models.CharField(max_length=100, null=True, blank=True)
    prec = models.CharField(max_length=100, null=True, blank=True)
    id_mg = models.CharField(max_length=100, null=True, blank=True)
    valor_solicitado = models.CharField(max_length=100, null=True, blank=True)
    n_parcela = models.CharField(max_length=10, null=True, blank=True)
    valor_parcela = models.CharField(max_length=100, null=True, blank=True)
    f_pagamento = models.CharField(max_length=100, null=True, blank=True)
    banco = models.CharField(max_length=100, null=True, blank=True)
    agencia = models.CharField(max_length=100, null=True, blank=True)
    n_conta = models.CharField(max_length=100, null=True, blank=True)
    t_conta = models.CharField(max_length=100, null=True, blank=True)
    tel = models.CharField(max_length=20, null=True, blank=True)
    cel = models.CharField(max_length=20, null=True, blank=True)
    mail = models.CharField(max_length=200, null=True, blank=True)
    obs = models.CharField(max_length=200, null=True, blank=True)
    responsavel = models.CharField(max_length=200, null=True, blank=True)
    data_cadastro = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.nome

class cliente_portabilidade(models.Model):
    id = models.AutoField(primary_key=True)
    orgao = models.CharField(max_length=200, null=True, blank=True)
    n_beneficio = models.CharField(max_length=200, null=True, blank=True)
    especie_beneficio = models.CharField(max_length=100, null=True, blank=True)
    uf_beneficio = models.CharField(max_length=2, null=True, blank=True)
    nome = models.CharField(max_length=200)
    cpf = models.CharField(max_length=14, null=True, blank=True)
    data_nasc = models.DateTimeField(null=True, blank=True)
    natural = models.CharField(max_length=200, null=True, blank=True)
    uf_natural = models.CharField(max_length=2, null=True, blank=True)
    endereco = models.CharField(max_length=200, null=True, blank=True)
    numero = models.CharField(max_length=30, null=True, blank=True)
    complemento = models.CharField(max_length=200, null=True, blank=True)
    bairro = models.CharField(max_length=100, null=True, blank=True)
    cidade = models.CharField(max_length=100, null=True, blank=True)
    uf_cidade = models.CharField(max_length=2, null=True, blank=True)
    cep = models.CharField(max_length=100, null=True, blank=True)
    tel = models.CharField(max_length=20, null=True, blank=True)
    cel = models.CharField(max_length=20, null=True, blank=True)
    mail = models.CharField(max_length=200, null=True, blank=True)
    banco_atual = models.CharField(max_length=200, null=True, blank=True)
    banco_portador = models.CharField(max_length=200, null=True, blank=True)
    ctt = models.CharField(max_length=100, null=True, blank=True)
    quitacao = models.CharField(max_length=100, null=True, blank=True)
    valor_parcela = models.CharField(max_length=100, null=True, blank=True)
    liquido = models.CharField(max_length=100, null=True, blank=True)
    banco_atual1 = models.CharField(max_length=200, null=True, blank=True)
    banco_portador1 = models.CharField(max_length=200, null=True, blank=True)
    ctt1 = models.CharField(max_length=100, null=True, blank=True)
    quitacao1 = models.CharField(max_length=100, null=True, blank=True)
    valor_parcela1 = models.CharField(max_length=100, null=True, blank=True)
    liquido1 = models.CharField(max_length=100, null=True, blank=True)
    banco_atual2 = models.CharField(max_length=200, null=True, blank=True)
    banco_portador2 = models.CharField(max_length=200, null=True, blank=True)
    ctt2 = models.CharField(max_length=100, null=True, blank=True)
    quitacao2 = models.CharField(max_length=100, null=True, blank=True)
    valor_parcela2 = models.CharField(max_length=100, null=True, blank=True)
    liquido2 = models.CharField(max_length=100, null=True, blank=True)
    banco_atual3 = models.CharField(max_length=200, null=True, blank=True)
    banco_portador3 = models.CharField(max_length=200, null=True, blank=True)
    ctt3 = models.CharField(max_length=100, null=True, blank=True)
    quitacao3 = models.CharField(max_length=100, null=True, blank=True)
    valor_parcela3 = models.CharField(max_length=100, null=True, blank=True)
    liquido3 = models.CharField(max_length=100, null=True, blank=True)
    f_pagamento = models.CharField(max_length=100, null=True, blank=True)
    banco = models.CharField(max_length=100, null=True, blank=True)
    agencia = models.CharField(max_length=100, null=True, blank=True)
    n_conta = models.CharField(max_length=100, null=True, blank=True)
    t_conta = models.CharField(max_length=100, null=True, blank=True)
    obs = models.CharField(max_length=200, null=True, blank=True)
    responsavel = models.CharField(max_length=200, null=True, blank=True)
    data_cadastro = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.nome