# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chica_estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chica_estoque.produto')),
            ],
        ),
    ]
