# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chica_estoque', '0002_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='retiradas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uso', models.CharField(choices=[(b'1', b'Proprio'), (b'2', b'Venda')], max_length=1)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chica_estoque.produto')),
            ],
        ),
    ]
