# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-19 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chica_estoque', '0003_retiradas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiradas',
            name='uso',
            field=models.CharField(choices=[('1', 'Proprio'), ('2', 'Venda')], max_length=1),
        ),
    ]
