# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-20 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0002_auto_20181220_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta_parcelada',
            name='estado',
            field=models.CharField(choices=[('1', 'Em Aberto'), ('2', 'Paga')], default=1, max_length=1),
        ),
    ]
