# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-20 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0003_conta_parcelada_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta_parcelada',
            old_name='estado',
            new_name='estate',
        ),
    ]
