# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0004_auto_20181220_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='agenda',
            name='estado',
            field=models.CharField(choices=[(b'1', b'Aberto'), (b'2', b'Desmarcado'), (b'3', b'Pago')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
