# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0006_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='pag',
            field=models.ManyToManyField(to='lavajato_agenda.pagamento'),
        ),
    ]
