# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0008_auto_20190109_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='conta_parcelada',
            name='parcelas_total',
            field=models.IntegerField(default=1),
        ),
    ]
