# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0009_auto_20190109_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
