# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_cliente', '0004_cliente_cpf'),
        ('lavajato_agenda', '0017_parcela_total_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lavajato_cliente.carro'),
            preserve_default=False,
        ),
    ]
