# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0018_agenda_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='pag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
