# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0019_parcela_pag'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='boleto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
