# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0020_agenda_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='boleto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
