# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0021_agenda_boleto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='obs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
