# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0022_agenda_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[(b'1', b'Dinheiro'), (b'2', b'Cartao Debito'), (b'3', b'Cartao Credito'), (b'4', b'Cartao Debito ELO'), (b'5', b'Cartao Credito ELO')], max_length=1),
        ),
    ]
