# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-16 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato_agenda', '0024_auto_20190215_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='pag_parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
